module.exports = {
	env: {
		"vitest-globals": true,
	},
	plugins: ["vitest"],
	extends: ["./base", "plugin:vitest/recommended"],
	rules: {
		"vitest/consistent-test-it": ["error", { fn: "test" }],
		"vitest/expect-expect": "error",
		"vitest/no-alias-methods": "error",
		"vitest/no-commented-out-tests": "error",
		"vitest/no-conditional-expect": "error",
		"vitest/no-conditional-tests": "error",
		"vitest/no-disabled-tests": "warn",
		"vitest/no-done-callback": "error",
		"vitest/no-focused-tests": "error",
		"vitest/no-identical-title": "error",
		"vitest/no-interpolation-in-snapshots": "error",
		"vitest/no-standalone-expect": "error",
		"vitest/no-test-return-statement": "error",
		"vitest/prefer-called-with": "error",
		"vitest/prefer-hooks-in-order": "error",
		"vitest/prefer-hooks-on-top": "error",
		"vitest/prefer-lowercase-title": "error",
		"vitest/prefer-spy-on": "error",
		"vitest/prefer-strict-equal": "error",
		"vitest/prefer-to-be": "error",
		"vitest/prefer-to-contain": "error",
		"vitest/prefer-to-have-length": "error",
		"vitest/require-hook": "error",
		"vitest/require-top-level-describe": "error",
		"vitest/valid-expect": "error",
		"vitest/valid-title": "error",
	},
};
